### ISSUE TITLE
Improve response on inputting invalid note id for edit

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/nota#21]
```
1) nota tests Users tests edit first note (invalid note id):
     Uncaught CastError: Cast to ObjectId failed for value "1111" at path "_id" for model "Task"
      at MongooseError.CastError (node_modules/mongoose/lib/error/cast.js:27:11)
      at ObjectId.cast (node_modules/mongoose/lib/schema/objectid.js:158:13)
      at ObjectId.SchemaType._castForQuery (node_modules/mongoose/lib/schematype.js:1088:15)
      at ObjectId.castForQuery (node_modules/mongoose/lib/schema/objectid.js:198:15)
      at ObjectId.SchemaType.castForQueryWrapper (node_modules/mongoose/lib/schematype.js:1045:15)
      at cast (node_modules/mongoose/lib/cast.js:269:32)

      at Query.cast (node_modules/mongoose/lib/query.js:3305:12)
      at castQuery (node_modules/mongoose/lib/query.js:3194:18)
      at _update (node_modules/mongoose/lib/query.js:3013:21)
      at Query.update (node_modules/mongoose/lib/query.js:2811:10)
      at _update (node_modules/mongoose/lib/model.js:2621:16)
      at Function.update (node_modules/mongoose/lib/model.js:2528:10)
      at routes/index.js:9:4139
      at routes/index.js:9:7358
      at node_modules/mongoose/lib/query.js:3118:18
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by jaylenw** [comment]
Closing as this repository will be archived.
